### Configuration File for CIBR-FLARE Project
## General Settings
git:
  remote:
    server: github.com
    branch: master
    ssh-key-private:
    user-name:
    user-email:
## Container Settings
container:
  name: flare-download-data-dev
  working-directory:
    server: 192.168.20.20
    repository: FLARE-forecast/test-data
    branch: master
    directory: fcre
    pre-run-pull: FALSE
    post-run-push: FALSE
## Parameters
lake_name_code: fcre
lake_name: Falling Creek Reservoir
noaa_location: flare-download-noaa-dev/test-data/fcre
realtime_insitu_location:
  git:
    remote:
      server: github.com
      repository: FLARE-forecast/FCRE-data
      branch: fcre-catwalk-data
      directory:
realtime_met_station_location:
  git:
    remote:
      server: github.com
      repository: FLARE-forecast/FCRE-data
      branch: fcre-metstation-data
      directory:
manual_data_location:
  git:
    remote:
      server: github.com
      repository: FLARE-forecast/FCRE-data
      branch: fcre-manual-data
      directory:
  manual-downloads:
  - url: https://portal.edirepository.org/nis/dataviewer?packageid=edi.389.4&entityid=c1db8816742823eba86696b29f106d0f
    file-name: Met_final_2015_2019.csv
realtime_inflow_data_location:
  git:
    remote:
      server: github.com
      repository: FLARE-forecast/FCRE-data
      branch: fcre-weir-data
      directory:
