### Configuration File for CIBR-FLARE Project
## General Settings
git:
  remote:
    server: github.com
    branch: master
    ssh-key-private:
    user-name:
    user-email:
## Container Settings
container:
  name: flare-download-noaa-dev
  working-directory:
    pre-run-pull: FALSE
    post-run-push: FALSE
    git:
      remote:
        server: 192.168.20.20
        port:
        repository: FLARE-forecast/test-data
        branch: master
        directory: fcre
        ssh-key-private:
        user-name:
        user-email:
  site:
    name: fcre
    latitude: 37.27
    longitude: 79.9
    output:
      git:
        remote:
          server: github.com
          port:
          repository: FLARE-forecast/test-data
          branch: flare-download-noaa
          directory:
          ssh-key-private:
          user-name:
          user-email:
