### Configuration File for CIBR-FLARE Project
## General Settings
git:
  remote:
    server: github.com
    branch: master
    ssh-key-private:
    user-name:
    user-email:
## Container Settings
container:
  name: flare-download-data-dev
  site:
    name: Falling Creek Reservoir
    code: fcre
    output:
      directory: fcre
## Parameters to Be Set in R
# parameters:
#   group1:
#     parameter1: value1
#     parameter2: value2
#   group2:
#     parameter3: value3
lake_name_code: fcre
lake_name: Falling Creek Reservoir
noaa_location: flare-download-noaa-dev/test-data/fcre
realtime_insitu_location:
  git:
  remote:
    server: github.com
    repository: FLARE-forecast/FCRE-data
    branch: fcre-catwalk-data
    directory:
realtime_met_station_location:
  git:
  remote:
    server: github.com
    repository: FLARE-forecast/FCRE-data
    branch: fcre-metstation-data
    directory:
manual_data_location:
  git:
  remote:
    server: github.com
    repository: FLARE-forecast/FCRE-data
    branch: fcre-manual-data
    directory:
realtime_inflow_data_location:
  git:
  remote:
    server: github.com
    repository: FLARE-forecast/FCRE-data
    branch: fcre-weir-data
    directory:
