### Configuration File for CIBR-FLARE Project

# If no value is entered for a key, the default value will be applied.

# General settings will be overwritten by container settings if different.

## General Settings
version                   :
ssh-key:
  private                 : # /home/$USER/.ssh/id_rsa (default for non-root), /root/.ssh/id_rsa (default for root)
git:
  remote:
    server                : # github.com (default)
    branch                : # test1 (default)
    user:
      name                : vahid-dan
      email               : v.daneshmand@gmail.com

## flare-external-driver-interface-noaa
flare-external-driver-interface-noaa:
  version                 : 0.1
  noaa:
    site:
      name                : fcre
      latitude            : 37.27
      longitude           : 79.9
  git:
    ssh-key:
      private             :
    remote:
      server              : github.com
      repository          : FLARE-forecast/test-data
      branch              : flare-external-driver-interface-noaa
      user:
        name              :
        email             :