#!/bin/bash

# Take Two Arguments and Return the First One That Is Not Null
function set_value (){
	([ ! -z $1 ] && echo $1) || echo $2
}

DOCKERHUB_ID="flareforecast"
CONTAINER_NAME="flare-external-driver-interface-noaa"
CONFIG_FILE="flare-config.yml"
CONTAINER_SCRIPT="flare-container.sh"
DIRECTORY_HOST="/opt/flare"
DIRECTORY_HOST_SHARED="/opt/flare/shared"
DIRECTORY_CONTAINER="/root/flare"
DIRECTORY_CONTAINER_SHARED="/root/flare/shared"

SSHKEY_PRIVATE_GENERAL=$(yq r $DIRECTORY_HOST_SHARED/$CONTAINER_NAME/$CONFIG_FILE ssh-key.private)
SSHKEY_PRIVATE_CONTAINER=$(yq r $DIRECTORY_HOST_SHARED/$CONTAINER_NAME/$CONFIG_FILE $CONTAINER_NAME.git.ssh-key.private)
SSHKEY_PRIVATE=$(set_value $SSHKEY_PRIVATE_CONTAINER $SSHKEY_PRIVATE_GENERAL)

cp -u $SSHKEY_PRIVATE $DIRECTORY_HOST_SHARED/$CONTAINER_NAME

DOCKER_RUN_COMMAND="docker run -v $DIRECTORY_HOST_SHARED/$CONTAINER_NAME:$DIRECTORY_CONTAINER_SHARED $DOCKERHUB_ID/$CONTAINER_NAME $DIRECTORY_CONTAINER/$CONTAINER_SCRIPT"

# Run Docker
$DOCKER_RUN_COMMAND
