### Configuration File for CIBR-FLARE Project

# If no value is entered for a key, the default value will be applied.

# General settings will be overwritten by container settings if different.

## General Settings
ssh-key:
  private                 : # /home/$USER/.ssh/id_rsa (default for non-root), /root/.ssh/id_rsa (default for root)
git:
  remote:
    server                : # github.com (default)
    branch                : # test1 (default)
    user:
      name                :
      email               :
        
## flare-push-test Container Settings
flare-push-test:
  git:
    ssh-key:
      private             :
    remote:
      server              : github.com
      repository          : CareyLabVT/FLARE-containers.git
      branch              : test2
      user:
        name              :
        email             :