#!/bin/bash

# Take 3 Arguments and Return the First One That Is Not Null
function set_value (){
	[[ ! -z $1 ]] && echo $1 || ([[ ! -z $2 ]] && echo $2 || echo $3)
}

# Change Directory to $DIRECTORY_CONTAINER
cd $(dirname $0)

DOCKERHUB_ID="flareforecast"
CONTAINER_NAME="flare-push-test"
CONFIG_FILE="flare-config.yml"
DIRECTORY_CONTAINER_SHARED="/root/flare/shared"

GIT_REMOTE_USER_NAME_DEFAULT=""
GIT_REMOTE_USER_NAME_GENERAL=$(yq r $DIRECTORY_CONTAINER_SHARED/$CONFIG_FILE git.remote.user.name)
GIT_REMOTE_USER_NAME_CONTAINER=$(yq r $DIRECTORY_CONTAINER_SHARED/$CONFIG_FILE $CONTAINER_NAME.git.remote.user.name)
GIT_REMOTE_USER_NAME=$(set_value $GIT_REMOTE_USER_NAME_CONTAINER $GIT_REMOTE_USER_NAME_GENERAL $GIT_REMOTE_USER_NAME_DEFAULT)

GIT_REMOTE_USER_EMAIL_DEFAULT=""
GIT_REMOTE_USER_EMAIL_GENERAL=$(yq r $DIRECTORY_CONTAINER_SHARED/$CONFIG_FILE git.remote.user.email)
GIT_REMOTE_USER_EMAIL_CONTAINER=$(yq r $DIRECTORY_CONTAINER_SHARED/$CONFIG_FILE $CONTAINER_NAME.git.remote.user.email)
GIT_REMOTE_USER_EMAIL=$(set_value $GIT_REMOTE_USER_EMAIL_CONTAINER $GIT_REMOTE_USER_EMAIL_GENERAL $GIT_REMOTE_USER_EMAIL_DEFAULT)

GIT_REMOTE_BRANCH_DEFAULT="test1"
GIT_REMOTE_BRANCH_GENERAL=$(yq r $DIRECTORY_CONTAINER_SHARED/$CONFIG_FILE git.remote.branch)
GIT_REMOTE_BRANCH_CONTAINER=$(yq r $DIRECTORY_CONTAINER_SHARED/$CONFIG_FILE $CONTAINER_NAME.git.remote.branch)
GIT_REMOTE_BRANCH=$(set_value $GIT_REMOTE_BRANCH_CONTAINER $GIT_REMOTE_BRANCH_GENERAL $GIT_REMOTE_BRANCH_DEFAULT)

GIT_REMOTE_SERVER_DEFAULT="github.com"
GIT_REMOTE_SERVER_GENERAL=$(yq r $DIRECTORY_CONTAINER_SHARED/$CONFIG_FILE git.remote.server)
GIT_REMOTE_SERVER_CONTAINER=$(yq r $DIRECTORY_CONTAINER_SHARED/$CONFIG_FILE $CONTAINER_NAME.git.remote.server)
GIT_REMOTE_SERVER=$(set_value $GIT_REMOTE_SERVER_CONTAINER $GIT_REMOTE_SERVER_GENERAL $GIT_REMOTE_SERVER_DEFAULT)

GIT_REMOTE_REPOSITORY_DEFAULT=""
GIT_REMOTE_REPOSITORY_GENERAL=$(yq r $DIRECTORY_CONTAINER_SHARED/$CONFIG_FILE git.remote.repository)
GIT_REMOTE_REPOSITORY_CONTAINER=$(yq r $DIRECTORY_CONTAINER_SHARED/$CONFIG_FILE $CONTAINER_NAME.git.remote.repository)
GIT_REMOTE_REPOSITORY=$(set_value $GIT_REMOTE_REPOSITORY_CONTAINER $GIT_REMOTE_REPOSITORY_GENERAL $GIT_REMOTE_REPOSITORY_DEFAULT)

SSHKEY_PRIVATE_DEFAULT=$([[ $EUID -eq 0 ]] && echo "/root/.ssh/id_rsa" || echo "/home/$USER/.ssh/id_rsa")
SSHKEY_PRIVATE_GENERAL=$(yq r $DIRECTORY_HOST_SHARED/$CONFIG_FILE ssh-key.private)
SSHKEY_PRIVATE_CONTAINER=$(yq r $DIRECTORY_HOST_SHARED/$CONFIG_FILE $CONTAINER_NAME.git.ssh-key.private)
SSHKEY_PRIVATE=$(set_value $SSHKEY_PRIVATE_CONTAINER $SSHKEY_PRIVATE_GENERAL $SSHKEY_PRIVATE_DEFAULT)

# Extract Directory Name from Remote Repository Name
GIT_DIRECTORY=$(awk -F. '{print $1}' <<< $(awk -F/ '{print $NF}' <<< $GIT_REMOTE_REPOSITORY))

# Extract Private SSH Key File Name from Full Path
SSHKEY_PRIVATE_FILE=$(awk -F/ '{print $NF}' <<< $SSHKEY_PRIVATE)
echo $SSHKEY_PRIVATE_FILE
echo $$DIRECTORY_CONTAINER_SHARED
echo $DIRECTORY_CONTAINER_SHARED/$SSHKEY_PRIVATE_FILE

# Set up SSH
mkdir -p /root/.ssh
cp -u $DIRECTORY_CONTAINER_SHARED/$SSHKEY_PRIVATE_FILE /root/.ssh
ssh-keyscan $GIT_REMOTE_SERVER > /root/.ssh/known_hosts

# Set up Git
git config --global user.name $GIT_REMOTE_USER_NAME
git config --global user.email $GIT_REMOTE_USER_EMAIL

# Clone Git Repository If Doesn't Exist
[ ! -d $GIT_DIRECTORY ] && git clone git@$GIT_REMOTE_SERVER:$GIT_REMOTE_REPOSITORY

# Do the Task
cd $GIT_DIRECTORY
git checkout $GIT_REMOTE_BRANCH
git pull
echo $(date) >> date.log
git add .
git commit -m "Add current date"
git push

# Remove .ssh Directory for Security Purposes
rm -rf /root/.ssh/