restart_file: .na
sim_name: test_glm_aed
forecast_days: 0
start_day_local: 2018-07-12
start_time_local: 07:00:00
end_day_local: .na
forecast_start_day_local: 2018-08-15
forecast_horizon: 16
forecast_project_id: test_glm_aed
forecast_sss_on: FALSE
forecast_location: /Users/quinn/Dropbox/Research/SSC_forecasting/FLARE_package/flare_lakes/fcre/glm_aed
execute_location: /Users/quinn/Dropbox/Research/SSC_forecasting/FLARE_package/flare_lakes/fcre/glm_aed/working_directory
